-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 20:50:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb3 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `project`.`personals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`personals` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_personal`),
  UNIQUE INDEX `idusers_UNIQUE` (`id_personal` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `project`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`services` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `name_service` VARCHAR(45) NOT NULL,
  `price_service` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_service`),
  UNIQUE INDEX `idservices_UNIQUE` (`id_service` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `project`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `personals_id_personal` INT NOT NULL,
  `services_id_service` INT NOT NULL,
  `clients_id_client` INT NOT NULL,
  `data_create_order` DATE NOT NULL,
  PRIMARY KEY (`id_order`, `personals_id_personal`, `services_id_service`, `clients_id_client`),
  UNIQUE INDEX `idorders_UNIQUE` (`id_order` ASC) VISIBLE,
  INDEX `fk_orders_personals_idx` (`personals_id_personal` ASC) VISIBLE,
  INDEX `fk_orders_services1_idx` (`services_id_service` ASC) VISIBLE,
  INDEX `fk_orders_clients1_idx` (`clients_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`clients_id_client`)
    REFERENCES `project`.`clients` (`id_client`),
  CONSTRAINT `fk_orders_personals`
    FOREIGN KEY (`personals_id_personal`)
    REFERENCES `project`.`personals` (`id_personal`),
  CONSTRAINT `fk_orders_services1`
    FOREIGN KEY (`services_id_service`)
    REFERENCES `project`.`services` (`id_service`))
ENGINE = InnoDB
AUTO_INCREMENT = 2018
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
